---
AWSTemplateFormatVersion: "2010-09-09" # <-------------------- don't touch

Description: 'Cfn Demo' # <-------------------- stack description

Resources:

  LambdaRole:  # <-------------------- define a resource
    Type: AWS::IAM::Role # <-------------------- define a resource type (check api in docs)
    Properties:
      RoleName:  "eyalCfnDemoRole" # <-------------------- edit this and add your name as a prefix
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ''
            Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: "PutMetricToCloudwatch"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "cloudwatch:PutMetricData"
                Resource: "*"