
Description: 'Hello World Lambda'

Parameters:

  Env:
    Type: String
    Default: ""
    MaxLength: 10

  FunctionName:
    Type: String

  BucketUrl:
    Type: String

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:  !Sub "${Env}CfnDemoRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ''
            Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: "PutMetricToCloudwatch"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "cloudwatch:PutMetricData"
                Resource: "*"

  NestedS3Stack:
    Type: AWS::CloudFormation::Stack # <------------------ Creating a Nested Stack
    Properties:
      Parameters: # <-------------------------- Passing parameters to the stack
        Env: !Ref Env
      TemplateURL: !Ref BucketUrl

  Lamda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub
        - "${Environment}${Name}Lambda"
        - Environment: !Ref Env
          Name: !Ref FunctionName
      Description: !Sub
        - "a lambda that writes to ${bucket} s3 bucket"
        - bucket: !GetAtt NestedS3Stack.Outputs.s3BucketName # <------------ Referencing a Nested Stacks Outputs
      Runtime: "python3.6"
      Handler: "index.handler"
      Role: !GetAtt LambdaRole.Arn
      Timeout: 30
      Code:
        ZipFile: |
          def handler(event, context):
              print("Hello Bros!")

Outputs:

   LambdaRoleArn:
    Value: !GetAtt LambdaRole.Arn
    Export:
      Name: !Sub "${Env}-demo-cfn-lambda-role-arn"
