
Description: 'Cfn Demo'

Parameters: # <----------------------- define parameter section

  Env: # <----------------- define a parameter
    Type: String
    Default: ""
    MaxLength: 10

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:  !Sub "${Env}CfnDemoRole" # <---------------- Reference the parameter
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ''
            Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: "PutMetricToCloudwatch"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "cloudwatch:PutMetricData"
                Resource: "*"